version 0.8.1 dated 2005-04-14

diff --git a/setup_beancounter b/setup_beancounter
--- a/setup_beancounter
+++ b/setup_beancounter
@@ -2,7 +2,7 @@
 #
 #   setup_beancounter --- Example usage of the beancounter tool
 #  
-#   Copyright (C) 2000 - 2004  Dirk Eddelbuettel <edd@debian.org>
+#   Copyright (C) 2000 - 2005  Dirk Eddelbuettel <edd@debian.org>
 #  
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -18,14 +18,30 @@
 #   along with this program; if not, write to the Free Software
 #   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
-#   $Id: setup_beancounter,v 1.31 2004/07/20 01:27:15 edd Exp $
+#   $Id: setup_beancounter,v 1.35 2005/04/14 03:19:33 edd Exp $
 
-# If we really want to be independent of the underlying database, this 
-# probably needs to written in Perl using DBI/DBD
+#  If we really want to be independent of the underlying database, this 
+#  probably needs to written in Perl using DBI/DBD
 #
-# This once started as being PostgreSQL specific
+#  This once started as being PostgreSQL specific ...
 #
-# MySQL patches by Mathias Weidner <mathias@weidner.in-bad-schmiedeberg.de>
+#  MySQL patches by Mathias Weidner <mathias@weidner.in-bad-schmiedeberg.de>
+#
+#  SQLite support was added some time in 2003.
+#
+#  As of 2005-04-13, two SQLite versions are supported: the new SQLite3 is the
+#  default, but with option -o $file, the previous version can be used.  This
+#  assumes a layout as on Debian systems, i.e.
+#
+#   				current v3	previous v2
+#      binary programs		sqlite3		sqlite
+#      Perl DBI Module		DBD::SQLite	DBD::SQLite2
+#
+#  i.e. a binary program 'sqlite3' is used to create a database for SQLite 3.*
+#  for which Perl code uses the DBD::SQLite module --- whereas 'sqlite' invokes
+#  the binary for the previous release SQLite 2.* for which Perl uses DBD::SQLite2
+#  If this differs on your system, you need to adjust the assignments of 
+#  DBCOMMAND below, and/or adjust BeanCounter.pm for the proper Perl module.
 
 # -------------------------- 'global' variables
 
@@ -42,9 +58,7 @@ then
 fi
 
 DATABASE='beancounter'
-VERSION='0.8.0'
-#DATABASE='testbean'
-#PASSWORD=
+VERSION='0.8.1'
 DBSYSTEM='PostgreSQL'
 #DBSYSTEM='MySQL'
 SCHEMA_ONLY=0
@@ -75,7 +89,8 @@ Usage: $progname [-m] [-n databasename] [-h]
 Options:
     -m		Use MySQL instead of PostgreSQL
     -n SOMENAME Create database as SOMENAME instead of beancounter
-    -l dbfile   Use SQLite as the backend with database file 'dbfile'
+    -l dbfile   Use SQLite3 (current version) as backend with file 'dbfile'
+    -o dbfile   Use SQLite (old v2) as backend with file 'dbfile'
     -s		Schema only -- Do not fill the database
     -h		Show this help
 EOF
@@ -353,7 +368,7 @@ function exit_if_exists
 	result=`echo 'show databases'| $DBCOMMAND | grep $DATABASE`
     elif [ "$DBSYSTEM" = "PostgreSQL" ]; then
 	result=`$DBCOMMAND template1 -l | grep $DATABASE`
-    elif [ "$DBSYSTEM" = "SQLite" ]; then
+    elif [ "$DBSYSTEM" = "SQLite" ] || [ "$DBSYSTEM" = "SQLite3" ]; then
 	result=`test -f $DATABASE && ls -1 $DATABASE`
     fi
     set -e
@@ -370,7 +385,7 @@ function exit_if_exists
 	echo "If you want to delete the exiting database, use"
 	echo "    dropdb $DATABASE       	for PostgreSQL"
 	echo "    mysqladmin -f drop $DATABASE	for MySQL"
-	echo "    rm $DATABASE	                for SQLite"
+	echo "    rm $DATABASE	                for SQLite, SQLite3"
 	echo ""
 	exit 1
     fi
@@ -453,7 +468,7 @@ function exit_if_no_mysql_user
 
 # ------------------------ 'main' code -------------------------------------
 
-while getopts ":mn:l:sh" opt
+while getopts ":mn:l:o:sh" opt
 do
     case $opt in
 	m)
@@ -467,7 +482,14 @@ do
 	l)
 	    DBSYSTEM='SQLite'
 	    DATABASE=$OPTARG
-	    echo "Now using $DBSYSTEM on $DATABASE"
+	    DBCOMMAND="sqlite3"
+	    echo "Now using (current) SQLite3 on $DATABASE"
+	    ;;
+	o)
+	    DBSYSTEM='SQLite2'
+	    DATABASE=$OPTARG
+	    DBCOMMAND="sqlite"
+	    echo "Now using (old) SQLite on $DATABASE"
 	    ;;
 	s)
 	    SCHEMA_ONLY=1
@@ -483,7 +505,6 @@ done
 
 BEANCOUNTER="beancounter --dbsystem $DBSYSTEM --dbname $DATABASE"
 
-DBCOMMAND=""
 if [ "$DBSYSTEM" = "PostgreSQL" ]; then		# if Postgres 
     if [ -z "$PASSWORD" ]; then
 	DBCOMMAND="psql -q"
@@ -497,8 +518,10 @@ elif [ "$DBSYSTEM" = "MySQL" ]; then 		# if MySQL
     else
 	DBCOMMAND="mysql -p$PASSWORD"
     fi
-elif [ "$DBSYSTEM" = "SQLite" ]; then 		# if SQLite 
-    DBCOMMAND="sqlite"
+elif [ "$DBSYSTEM" = "SQLite" ]; then 		# if SQLite v3
+    true					# nothing to do
+elif [ "$DBSYSTEM" = "SQLite2" ]; then 		# if SQLite v2
+    true					# nothing to do
 else
     echo ""
     echo "*** Error: Unsupported database system ***"
@@ -520,27 +543,27 @@ fi
 
 # test if $DATABASE exists and exit if true
 exit_if_exists
-			
-echo "Creating $DATABASE database"
-if [ "$DBSYSTEM" = "PostgreSQL" ]; then
-    execute "createdb $DATABASE"
-elif [ "$DBSYSTEM" = "MySQL" ]; then
-    echo "create database $DATABASE;" | $DBCOMMAND 
-# NB deleting db under MySQL is:  mysqladmin drop beancounter_test -p$PASSWORD
-# grant access to $DATABASE db
-#GRANT="grant select,delete,insert,update on $DATABASE.* to $USER@localhost"
-#echo $GRANT | $DBCOMMAND
-elif [ "$DBSYSTEM" = "SQLite" ]; then
-    true # do nothing
+
+if [ "$DBSYSTEM" = "PostgreSQL" ] || [ "$DBSYSTEM" = "MySQL" ]; then
+    echo "Creating $DATABASE database"
+    if [ "$DBSYSTEM" = "PostgreSQL" ]; then
+        execute "createdb $DATABASE"
+    elif [ "$DBSYSTEM" = "MySQL" ]; then
+        echo "create database $DATABASE;" | $DBCOMMAND 
+    # NB deleting db under MySQL is:  mysqladmin drop beancounter_test -p$PASSWORD
+    # grant access to $DATABASE db
+    #GRANT="grant select,delete,insert,update on $DATABASE.* to $USER@localhost"
+    #echo $GRANT | $DBCOMMAND
+    fi
+    echo ""
 fi
-echo ""
 
 echo "Creating $DATABASE database tables"
 if [ "$DBSYSTEM" = "PostgreSQL" ]; then
     create_postgres_tables 
 elif [ "$DBSYSTEM" = "MySQL" ]; then
     create_mysql_tables 
-elif [ "$DBSYSTEM" = "SQLite" ]; then
+elif [ "$DBSYSTEM" = "SQLite2" ] || [ "$DBSYSTEM" = "SQLite" ]; then
     create_sqlite_tables
 fi
 
@@ -549,21 +572,22 @@ if [ "$SCHEMA_ONLY" -eq 1 ]; then
     exit 0
 fi
 
-# testing database access from Perl
-echo "Verifying database access from Perl"
-set +e
-beancounter checkdbconnection
-rc="$?"
-if [ "$rc" != 1 ]
-then
-#    echo "Successful, continuing"
-#else
-    echo "Failure -- please check database permission, possible requirement of"
-    echo "a password and other sources of failure to establish a connection."
-    exit 1
+if [ "$DBSYSTEM" = "PostgreSQL" ] || [ "$DBSYSTEM" = "MySQL" ]; then
+    # testing database access from Perl
+    echo "Verifying database access from Perl"
+    set +e
+    beancounter checkdbconnection
+    rc="$?"
+    if [ "$rc" != 1 ]
+    then
+       #    echo "Successful, continuing"
+       #else
+       echo "Failure -- please check database permission, possible requirement of"
+       echo "a password and other sources of failure to establish a connection."
+       exit 1
+    fi
+    set -e
 fi
-set -e
-
 
 # insert the DJIA stocks into the indices table
 echo "Filling $DATABASE database tables with DJIA stocks"
@@ -615,7 +639,8 @@ of the features of B<beancounter>.
 =head1 OPTIONS
 
  -m        Use MySQL as the backend over the default PostgreSQL
- -l dbfile Use SQLite as the backend with database file 'dbfile'
+ -l dbfile Use SQLite \(version 3 or later\) with database file 'dbfile'
+ -o dbfile Use SQLite2 \(compatibility mode\) with database file 'dbfile'
  -n name   Use name as the database instead of beancounter
  -s        Do not fill the database, only create its schema
  -h        Show a simple help message
